name: SCA - Dependency Check
on:
  push:
  workflow_dispatch:
  
jobs:
 SCA_caller:
      uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/sca_bt.yml@main
      secrets:
       NVD_API_KEY: ${{ secrets.NVD_API_KEY }}