name: Secret Scanning - Gitleaks Caller
on:
  push:
  workflow_dispatch:

jobs:
  Secret_Scanning_caller:
      uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/secretscanning.yml@main